---
title: "Fish_Community_Size_Structure"
author: "johanna.wren@noaa.gov"
format:
  docx:
    reference-doc: SAFE-Reference-Doc.docx
---

## Fish community size structure

```{r}
#| include: false
### Load libraries
library(tidyverse)
library(lubridate)
library(rje)
library(zoo)

```

```{r}
#| include: false
# Set report year (RptYr), to make things easier
RptYr <- 2024

# Set path to variable: Median_Phytoplankton_Size
# This is where the data are and where the plots will go
Dir <- here("Fish_Community_Size_Structure")
```
<!--
# Here we import data saved locally and filter out only bigeye tuna (coded as species 6 in the dealer dataset) for deep-set trips onlu and that we don't include trips in the current year. 
-->
```{r}
#| include: false
# Import the data from saved files
setwd(file.path(mainDir, 'Data'))
dealerRaw <- readRDS(paste0('SAFE_dealer_', yr, '.rds'))
logbookRaw <- readRDS(paste0('SAFE_logbook_', yr, '.rds'))

# Filter data to bigeye only for deep set trips before 2023
dealerRaw <- dealerRaw %>%
  filter(REPORT_DATE < as.Date(paste0(yr+1, '-01-01')),
         SPECIES_FK == 6, 
         SET_TYPE == 'D')

# Make sure we only have information from the Hawaii fleet for trips spanning 2000- 2023
logbookRaw <- logbookRaw %>%
  filter(LANDYR >= 2000,  LANDYR <= yr, FLEET == 'HI', )
```

<!--
# Analyze data

## Convert weights from gilld & gutted to whole fish weights

Dealer weights are reported in lbs for gilled and gutted fresh, chilled fish. Here we convert their weight to whole fish weight using a non-linear conversion from *Langley et al. 2006* table 8. 

NOTE: Dealer data comes with a conversion factor (I kept it in the raw dataset) but it's fixed and for multiple entries it's quite complicated. I opted to use the Langley conversion here rather than the standard conversion factor reported because I felt it was most consistent and a better fit. 

NOTE 2: in 2024 Removing any records of negative NUM_SOLD. Total of 28 records, all in 2023.
-->
```{r}
dealer <- dealerRaw %>%
  filter(NUM_SOLD >= 0) %>% 
  mutate(Weight_GilGut=MEAN_SOLD_WEIGHT/2.204624, 
         Weight_Whole=1.274959*round(Weight_GilGut)^0.960613, 
         Year=year(REPORT_DATE), 
         Quarter=quarter(REPORT_DATE)) %>%
  uncount(NUM_SOLD) %>%   # unbin the binned records
  mutate(NUM_SOLD=1) %>%  # make a num sold column since it was removed during the uncount operation
  select(TRIP_NUM, REPORT_DATE, NUM_SOLD, Weight_Whole, Year, Quarter) %>%
  mutate(Weight_Whole=ifelse(Weight_Whole > 100, 100, Weight_Whole))

```

<!--
## Calculate Age
This is only used to mark the dashed age lines in the figure

Here we calculate the age of fish from the weight. First we use a Richards growth parameterization from an intergrated analysis in Aires-da-Silva et al. 2015 getting an length from age information:

$$L_a=L_\infty(1+\frac{1}{p}e^{-K(a-t_0)})^{-p}$$
where $L_\infty$ is the asymptotic length, $K$ is the growth coefficient, $t_0$ is the inflection point on the curve, and $p$ is the shape parameter related to the ratio $L_a/L_\infty$

Then we convert the length given from the growth equation above to a weight using data from Phoebe that she derived based on the Hawaii deep-set fishery. 
-->
```{r}
# using Aires-da-Silva 2015 Richard growth model using integrated data
a <- 1:7   # age in years
Linf <- 200.8               # asymptotic length
K <- 0.44                   # growth coefficient
t0 <- 1.26                  # inflexion point on the curve
p <- -4.27                  # shape parameter related to the ratio La/Linf
La <- Linf*(1+(1/p)*exp(-K*(a-t0)))^(-p)

# Convert from Length to weight using Phoebe's numbers for the Hawaii fishery
Weight <- 0.0187*La^2.9605  # these numbers are from phoebe
WeightAge <- round(Weight)/1000
```

<!--
## Calculate effort
Calculating both climatological quarterly efforts and annual quarter efforts.
-->
```{r}
# Make a trip level dataset
logbook <- logbookRaw %>% 
  mutate(Quarter=quarter(LANDMON), Year=LANDYR) %>%
  filter(!RSCH_EXPMTL_CODE %in% c('R', 'X'), FLEET == 'HI', SET_TYPE == 'D')
  
# Calculate quarterly climatology effort
efrtTot <-  logbook %>%
  filter(Year <= 2009) %>%
  group_by(Quarter) %>%
  summarise(EffortClim=sum(HOOKSSET/1000, na.rm=T))
 
# Calculate quarterly annual efforts 
efrtYr <- logbook %>%
  group_by(Year, Quarter) %>%
  summarise(Effort=sum(HOOKSSET/1000, na.rm=T))
```

<!--
## Histograms
Calculating quarterly climatological histograms for use in the figures. Calculate these outside the loop since they are the same for each quarter. 
-->
```{r}
# Calculate quarterly climatology histograms
cCPUE <- list()
for (q in 1:4) {
  cCPUE[[q]] <- dealer %>% 
    filter(Quarter==q, Year <= 2009) %>% 
    select(Weight_Whole) %>% 
    lapply(hist, plot=F)
  cCPUE[[q]]$Weight_Whole$CPUE <- cCPUE[[q]]$Weight_Whole$counts/efrtTot$EffortClim[q]
}
```

